# commit to be tagged for the new release
commit = "HEAD"

project_name = "pkgs"
github_repo = "siderolabs/pkgs"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v1.12.0"
# pre_release = true

# [notes]
